spring:
  application:
    name: crypto-weather
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: weather_group
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/crypto_weather_db
    username: root
    password: ${DB_PASS:testtest}

  thymeleaf:
    cache: false
weather_apikey: 813eff2b8a174601b28101610240407