spring:
  application:
    name: crypto-weather
  kafka:
    producer:
      key-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
    bootstrap-servers: localhost:29092
    consumer:
      group-id: weather_group
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  datasource:
    url: jdbc:mysql://localhost:3306/crypto_weather_db
    username: root
    password: ${DB_PASS:testtest}

  thymeleaf:
    cache: false
weather_apikey: 813eff2b8a174601b28101610240407