spring:
  application:
    name: crypto-weather
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/crypto_weather_db
    username: root
    password: 1234