spring:
  application:
    name: crypto-weather
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/crypto_weather_db
    username: root
    password: ${DB_PASS:1234}

  thymeleaf:
    cache: false
